# collector-web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-frontend
  namespace: collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector-frontend
  template:
    metadata:
      labels:
        app: collector-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: frontend
          image: ghcr.io/pc3-cizm/collector-frontend:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: collector-frontend
  namespace: collector
spec:
  selector:
    app: collector-frontend
  ports:
    - port: 80
      targetPort: 80
