name: CD - Deploy Collector to Azure Container Apps

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ==========================
      # DEPLOY EXISTING IMAGES
      # ==========================

      - name: Deploy DB
        run: |
          az containerapp update \
            -n collector-db \
            -g rg-test-collector \
            --image ghcr.io/pc3-cizm/collector-db:develop

      - name: Deploy Backend
        run: |
          az containerapp update \
            -n collector-backend \
            -g rg-test-collector \
            --image ghcr.io/pc3-cizm/collector-backend:develop

      - name: Deploy Frontend
        run: |
          az containerapp update \
            -n collector-frontend \
            -g rg-test-collector \
            --image ghcr.io/pc3-cizm/collector-frontend:develop
