name: Trigger auto deployment for collector-db

on:
  push:
    branches:
      [ master ]
    paths:
      - 'docker/postgres/**'
      - '.github/workflows/collector-db-AutoDeployTrigger-640bcb7c-2b6c-4cd9-8695-65a31145ea46.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.COLLECTORDB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COLLECTORDB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COLLECTORDB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/docker/postgres
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.COLLECTORDB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COLLECTORDB_REGISTRY_PASSWORD }}
          containerAppName: collector-db
          resourceGroup: rg-test-collector
          imageToBuild: ghcr.io/pc3-cizm/collector-db:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_